services:
  db:
    image: "mysql:8"
    ports: 
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - prisma-network

  backend:
    build:
      context: ./backend-api
    env_file:
      - backend-api/.env
    ports: 
      - "8000:8000"
    networks:
      - prisma-network
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma db push && npm run seed && npm start"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

networks:
  prisma-network:

volumes:
  mysql_data: